items:
- path: home
  title: AdminTool
  items:
  - title: Home
    route: /
  - path: about
    title: About
    items:
    - title: Admin Tool Context
      route: /context
    - title: Admin Tool Clients
      route: /clients
    - title: Help
      route: /help
- path: resources
  title: AWS
  items:
  - title: Infrastructure Reports
    route: /infra
    breadcrumb: true
    description: |
      ## Reports on the AWS infrastructure
      - [Instances](/infra/instances?program=uc3)
      - [SSM Parameters](/infra/parameters)
  - title: UC3 Instances
    route: /infra/instances?program=uc3
  - title: UC3 SSM Parameters
    route: /infra/parameters
