items:
- path: home
  title: AdminTool
  items:
  - title: UC3 Server Listing and SSM Registry
    route: /
  - path: about
    title: About
    items:
    - title: Admin Tool Context
      route: /context
    - title: Admin Tool Clients
      route: /clients
    - title: Help
      route: /help
- path: resources
  title: Infrastructure Reports
  route: /infra
  breadcrumb: true
  items:
  - title: UC3 Instances
    route: /infra/instances?program=uc3
  - title: Merritt Instances
    route: /infra/instances?program=uc3&service=mrt
  - title: Merritt SSM Parameters
    route: /infra/parameters
