# frozen_string_literal: true

source 'http://rubygems.org'
ruby '~> 3.2'

gem 'anbt-sql-formatter'
gem 'aws-sdk-codeartifact'
gem 'aws-sdk-ec2'
gem 'aws-sdk-ecr'
gem 'aws-sdk-ecs'
gem 'aws-sdk-elasticloadbalancingv2'
gem 'aws-sdk-lambda'
gem 'aws-sdk-s3'
gem 'aws-sdk-ssm'
gem 'bigdecimal'
gem 'csv'
gem 'debug'
gem 'json'
gem 'mrt-zk', git: 'https://github.com/CDLUC3/mrt-zk.git', tag: '2.4.15'
gem 'mustache'
gem 'mysql2'
gem 'net-ldap'
gem 'nokogiri'
gem 'octokit'
gem 'puma'
gem 'rack'
gem 'rack-contrib'
gem 'rackup'
gem 'redcarpet'
gem 'rubocop'
gem 'rubysl-base64'
gem 'rubyzip'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'yaml'
gem 'zk'
gem 'zookeeper'

# These are the dependencies that are used only for unit tests.
group :test do
  gem 'rack-test'
  gem 'rspec'
end
