dbconf: 
  adapter: mysql2
  encoding: utf8mb4
  host: {{host}}
  database: {{database}}
  pool: 25
  port: 3306
  username: {{username}}
  password: {{password}}
dbconfZZ: 
  adapter: mysql2
  encoding: utf8mb4
  host: 127.0.0.1
  database: test
  pool: 25
  port: 3306
  username: user
  password: password
