queries:
- route: /queries/campus
  name: Campus Counts
  menuitems:
  - menupath: /reports/repository
  sql: |
    select
      distinct
      ogroup as campus,
      count(distinct inv_collection_id) num_colls,
      sum(count_files) files,
      sum(billable_size) size
    from
      owner_coll_mime_use_details
    group by
      ogroup
    order by
      ogroup
- route: /queries/collections
  name: List Collections with Counts
  menuitems:
  - menupath: /reports/repository
  sql: |
    select
      distinct
      ogroup,
      inv_collection_id,
      mnemonic,
      collection_name,
      sum(count_files) files,
      sum(billable_size) size
    from
      owner_coll_mime_use_details
    group by
      ogroup,
      inv_collection_id,
      mnemonic,
      collection_name
    order by
      ogroup,
      mnemonic
- route: /queries/owners
  name: Owner Counts
  menuitems:
  - menupath: /reports/repository
  sql: |
    select
        ogroup,
        inv_owner_id as owner_id,
        own_name,
        sum(count_files) files,
        sum(billable_size) size
      from
        owner_coll_mime_use_details
      group by
        ogroup,
        owner_id,
        own_name
      order by
        ogroup,
        own_name
