docker: &docker
  admin_password: 
    val: password
  host:
    val: ldap
  port:
    val: 1389
  default_read:
    val: merritt-test, anonymous
  default_write:
    val: merritt-test
  default_download:
    val: merritt-test, anonymous
  default_admin:
    val: merritt-test

  _fixed: &fixed
    admin_user: "cn=Directory Manager"
    group_base: "ou=mrt-classes,ou=uc3,dc=cdlib,dc=org"
    user_base: "ou=People,ou=uc3,dc=cdlib,dc=org"
    inst_base: "o=institutions,ou=uc3,dc=cdlib,dc=org"
    ark_minter_url: "http://noid.cdlib.org/nd/noidu_p9"
    guest_password: guest
    guest_user: anonymous
    connect_timeout: 15
dockerlocal:
  <<: *docker
ecs-dev:
  <<: *docker
ecs-dbsnapshot:
  <<: *docker
ecs-ephemeral:
  <<: *docker
ecs-stg:
  admin_password: 
    ssm: /uc3/mrt/stg/ldap/admin-password
  host:
    env: HOST_LDAP
  port: 
    val: 1636
  encryption:
    val: simple_tls
  default_read:
    ssm: /uc3/mrt/stg/ldap/default-read
  default_write:
    ssm: /uc3/mrt/stg/ldap/default-write
  default_download:
    ssm: /uc3/mrt/stg/ldap/default-download
  default_admin:
    ssm: /uc3/mrt/stg/ldap/default-admin
  _fixed:
    <<: *fixed
ecs-prd:
  admin_password: 
    ssm: /uc3/mrt/prd/ldap/admin-password
  host:
    env: HOST_LDAP
  port: 
    val: 1636
  encryption: 
    val: simple_tls
  default_read:
    ssm: /uc3/mrt/prd/ldap/default-read
  default_write:
    ssm: /uc3/mrt/prd/ldap/default-write
  default_download:
    ssm: /uc3/mrt/prd/ldap/default-download
  default_admin:
    ssm: /uc3/mrt/prd/ldap/default-admin
  _fixed:
    <<: *fixed
default:
  <<: *docker 