items:
- path: home
  title: AdminTool
  items:
  - title: Home
    route: /
  - title: Consistency Reports
    route: /queries/consistency
    breadcrumb: true
    description: |
      ## Consistency Reports
      - [Object Replication - Only 2 Copies](/queries/consistency/replication/objects-2)
      - [Object Replication - Only 1 Copy](/queries/consistency/replication/objects-1)
      - [Object Replication - 4 Copies](/queries/consistency/replication/objects-4)
      - [File Replication - Only 2 Copies](/queries/consistency/replication/files-2)
      - [File Replication - Only 1 Copy](/queries/consistency/replication/files-1)
      - [File Replication - 4 Copies](/queries/consistency/replication/files-4)
      - [Version Clobber](/queries/consistency/version-clobber)
      - [Objects no local id](/queries/consistency/objects-no-local-id)
      - [Local id no Ark](/queries/consistency/local-id-no-ark)
      - [Objects linked to multiple Collections](/queries/consistency/objects-linked-to-multiple-collections)
  - title: Batches
    route: /queue/batches
    tbd: true
  - title: Jobs
    route: /queue/jobs-by-collection
    tbd: true
  - path: about
    title: About
    items:
    - title: Admin Tool Context
      route: /context
    - title: Admin Tool Clients (VPC)
      route: /clients
    - title: Admin Tool Clients (No VPC)
      route: /infra/clients-no-vpc
    - title: Help
      route: /help
- path: source
  title: Source
  items:
  - title: Source Code Repo
    route: /source
- path: reports
  title: Reports
  items:
  - path: repository
    title: Repository
    items:
    - title: Repository Queries
      route: /queries/repository
      breadcrumb: true
      description: |
        ## Reports on the repository
        - [Campus Files/Bytes](/queries/repository/campus)
        - [Campus Objects](/queries/repository/campus-objects)
        - [Collections Files/Bytes](/queries/repository/collections)
        - [Collections Objects](/queries/repository/collections-objects)
        - [Owner Files/Bytes](/queries/repository/owners)
        - [Mime Types](/queries/repository/mimes)
        - Invoices
    - title: Campus Files/Bytes
      route: /queries/repository/campus
    - title: Campus Objects
      route: /queries/repository/campus-objects
    - title: Collections Files/Bytes
      route: /queries/repository/collections
    - title: Collection Details
      route: /queries/repository/collection
      breadcrumb: true
      description: |
        ## Collection Details
    - title: Recent Objects
      route: /queries/repository/objects
    - title: Object Details
      route: /queries/repository/object
      breadcrumb: true
    - title: Object Details - Search by Ark
      route: /queries/repository/object-ark
      breadcrumb: true
    - title: Objects - Search by erc-what
      route: /queries/repository/objects-erc-what
      breadcrumb: true
    - title: Objects - Search by erc-who
      route: /queries/repository/objects-erc-who
      breadcrumb: true
    - title: Objects - Search by erc-when
      route: /queries/repository/objects-erc-when
      breadcrumb: true
    - title: Objects - Search by filename
      route: /queries/repository/objects-by-filename
      breadcrumb: true
    - title: Objects - Search by Local Id
      route: /queries/repository/objects-localid
      breadcrumb: true
    - title: Objects - Search by Container
      route: /queries/repository/objects-container
      breadcrumb: true
    - title: Object Details
      route: /queries/repository/object
      breadcrumb: true
      description: |
        ## Object Details
    - title: Collections Objects
      route: /queries/repository/collections-objects
    - title: Owner Files/Bytes
      route: /queries/repository/owners
    - path: mimes
      title: Mime Types
      route: /queries/repository/mimes
      breadcrumb: true
      description: |
        The full mime query will bring back too many results.  

        You must filter by 
        - campus
        - mime group
      items:
      - path: campus
        title: By Campus
        route: /queries/repository/mimes/campus
        breadcrumb: true
        items:
        - title: CDL
          route: /queries/repository/mimes/campus/CDL
        - title: UCB
          route: /queries/repository/mimes/campus/UCB
        - title: UCD
          route: /queries/repository/mimes/campus/UCD
        - title: UCI
          route: /queries/repository/mimes/campus/UCI
        - title: UCLA
          route: /queries/repository/mimes/campus/UCLA
        - title: UCM
          route: /queries/repository/mimes/campus/UCM
        - title: UCSB
          route: /queries/repository/mimes/campus/UCSB
        - title: UCSC
          route: /queries/repository/mimes/campus/UCSC
        - title: UCSD
          route: /queries/repository/mimes/campus/UCSD
        - title: UCSF
          route: /queries/repository/mimes/campus/UCSF
        - title: Other
          route: /queries/repository/mimes/campus/Other
      - path: group
        title: By Mime Group
        route: /queries/repository/mimes/group
        breadcrumb: true
        items:
        - title: software
          route: /queries/repository/mimes/group/software
        - title: audio
          route: /queries/repository/mimes/group/audio
        - title: container
          route: /queries/repository/mimes/group/container
        - title: data
          route: /queries/repository/mimes/group/data
        - title: geo
          route: /queries/repository/mimes/group/geo
        - title: image
          route: /queries/repository/mimes/group/image
        - title: software
          route: /queries/repository/mimes/group/software
        - title: text
          route: /queries/repository/mimes/group/text
        - title: video
          route: /queries/repository/mimes/group/video
        - title: web
          route: /queries/repository/mimes/group/web
    - title: Campus Invoices
      route: /repository/invoices
      tbd: true
    - title: Ingests over Time
      route: /ingest/ingests-over-time
      tbd: true
  - path: consistency
    title: Consistency
    items:
    - path: replication
      title: Replication
      items:
      - title: Object Replication - Only 2 Copies
        route: /queries/consistency/replication/objects-2
      - title: Object Replication - Only 1 Copy
        route: /queries/consistency/replication/objects-1
      - title: Object Replication - 4 Copies
        route: /queries/consistency/replication/objects-4
      - title: File Replication - Only 2 Copies
        route: /queries/consistency/replication/files-2
      - title: File Replication - Only 1 Copy
        route: /queries/consistency/replication/files-1
      - title: File Replication - 4 Copies
        route: /queries/consistency/replication/files-4
    - path: objects
      title: Object Composition
      items:
      - title: Version Clobber
        route: /queries/consistency/version-clobber
      - title: Objects no local id
        route: /queries/consistency/objects-no-local-id
      - title: Local id no Ark
        route: /queries/consistency/local-id-no-ark
        tbd: true
      - title: Objects linked to multiple Collections
        route: /queries/consistency/mult-colls
  - path: use-cases
    title: Use Cases
    items:
    - title: Largest Objects
      route: /queries/use-cases/largest-objects
    - title: Objects with most files
      route: /queries/use-cases/most-files
    - title: Objects with largest individual files
      route: /queries/use-cases/largest-files
    - title: Objects with non-ascii erc-what (mrt-demo)
      route: /queries/use-cases/non-ascii-erc-what-mrt-demo
    - title: Objects with non-ascii pathname (mrt-demo)
      route: /queries/use-cases/non-ascii-pathname-mrt-demo
    - title: Objects with long mime types - selected collections
      route: /queries/use-cases/long-mime-type-selected-collections
    - title: Objects with long pathnames - selected collections
      route: /queries/use-cases/long-pathname-selected-collections
- path: Operations
  title: Operations
  items:
  - path: ingest-queue
    title: Ingest Queue
    items:
    - title: Pause
      route: /ingest/pause
      tbd: true
    - title: Unpause
      route: /ingest/unpuse
      tbd: true
    - title: Ingest Batches
      route: /ingest/batches
      tbd: true
    - title: Jobs by Collection
      route: /ingest/jobs-by-collection
      tbd: true
    - title: Cleanup Queue
      route: /ingest/cleanup-queue
      tbd: true
    - title: Recent Ingests
      route: /ingest/recent-ingests
      tbd: true
    - title: Ingest Folders
      route: /ingest/folders
      tbd: true
  - path: access-queue
    title: Access Queue
    items:
    - title: Pause
      route: /access/pause
      tbd: true
    - title: Unpause
      route: /access/unpause
      tbd: true
    - title: View Queue
      route: /access/jobs
      tbd: true
    - title: Cleanup Queue
      route: /access/cleanup-queue
      tbd: true
  - path: replication-queue
    title: Replication Queue
    items:
    - title: Queued
      route: /replication/queued
      tbd: true
    - title: In Progress
      route: /replication/in-progress
      tbd: true
    - title: Failed
      route: /replication/failed
      tbd: true
    - title: Recent Performance
      route: /replication/recent-performance
      tbd: true
  - path: audit-queue
    title: Audit Queue
    items:
    - title: Oldest Audit Check
      route: /audit/oldest-audit-check
      tbd: true
    - title: Recent Performance
      route: /audit/recent-performance
      tbd: true
    - title: Active Batches
      route: /audit/active-batches
      tbd: true
    - title: Counts by State
      route: /audit/counts-by-state
      tbd: true
  - title: Object Locks
    route: /objects/locks
    tbd: true
  - path: collections
    title: Collections
    items:
    - title: Profiles
      route: /collections/profiles
      tbd: true
    - title: Collection Config
      route: /collections/config
      tbd: true
    - title: Storage Node Config
      route: /collections/storage-node-config
      tbd: true
    - title: Non standard primary config
      route: /collections/primary-config
      tbd: true
    - title: Non standard secondary config
      route: /collections/secondary-config
      tbd: true
    - title: Node cleanup needed
      route: /collections/node-cleanup-needed
      tbd: true
    - title: Collection Locks
      route: /collections/locks
      tbd: true
  - path: storage
    title: Storage
    items:
    - title: Storage Nodes
      route: /storage/nodes
      tbd: true
    - title: Test Storage Nodes
      route: /storage/test-nodes
      tbd: true
    - title: Storage Scans
      route: /storage/scans
      tbd: true
- path: Internals
  title: Internals
  items: 
  - path: zookeeper
    title: ZooKeeper
    items:
    - title: Node Names
      route: /zk/node-names
      tbd: true
    - title: Node Data
      route: /zk/node-data
      tbd: true
    - title: Locks
      route: /zk/locks
      tbd: true
    - title: Orphan Report
      route: /zk/orphan-report
      tbd: true
  - path: ldap
    title: LDAP
    items:
    - title: Users
      route: /ldap/users
      tbd: true
    - title: Groups
      route: /ldap/groups
      tbd: true
    - title: Collections
      route: /ldap/collections
      tbd: true
  - title: LDAP Certs
    route: /infra/certs
    tbd: true
  - title: Merritt Server State
    route: /services/state
    tbd: true
  - title: Merritt Deployment State
    route: /services/deployment
    tbd: true
  - title: SSM Usage
    route: /infra/ssm-usage
    tbd: true
  - title: OpenSearch Usage
    route: /infra/opensearch-usage
    tbd: true
- path: resources
  title: AWS
  items:
  - title: Infrastructure Reports
    route: /infra
    breadcrumb: true
    description: |
      ## Reports on the AWS infrastructure
      - [Instances](/infra/instances)
      - [SSM Parameters](/infra/parameters)
      - [Buckets](/infra/buckets)
      - [Lambda Functions](/infra/functions)
      - [Load Balancers](/infra/elbs)
  - title: UC3 Instances
    route: /infra/instances
  - title: UC3 SSM Parameters
    route: /infra/parameters
  - title: UC3 Buckets
    route: /infra/buckets
  - title: UC3 Lambda Functions
    route: /infra/functions
  - title: UC3 Load Balancers
    route: /infra/elbs