# https://github.com/brianmario/mysql2?tab=readme-ov-file#connection-options
docker: &docker
  host: 
    val: db-container
  database: 
    val: billing
  username: 
    val: user
  password: 
    val: password
  base_url:
    env: base_url
  read_timeout:
    val: 120
  write_timeout:
    val: 120
ecs-ephemeral:
  <<: *docker
dockerlocal:
  host: 
    val: 127.0.0.1
  database: 
    val: billing
  username: 
    val: user
  password: 
    val: password
  base_url:
    env: base_url
  read_timeout:
    val: 120
  write_timeout:
    val: 120
ecs-dev:
  host: 
    ssm: /uc3/mrt/ecs/billing/db-host
  database: 
    ssm: /uc3/mrt/ecs/billing/db-name
  username: 
    ssm: /uc3/mrt/ecs/billing/readwrite/db-user
  password: 
    ssm: /uc3/mrt/ecs/billing/readwrite/db-password
  base_url:
    env: base_url
  read_timeout:
    val: 120
  write_timeout:
    val: 120
ecs-dbsnapshot:
  host: 
    ssm: /uc3/mrt/dev/billing/db-host
  database: 
    ssm: /uc3/mrt/dev/billing/db-name
  username: 
    ssm: /uc3/mrt/dev/billing/readwrite/db-user
  password: 
    ssm: /uc3/mrt/dev/billing/readwrite/db-password
  base_url:
    env: base_url
  read_timeout:
    val: 600
  write_timeout:
    val: 600
ecs-stg:
  host: 
    ssm: /uc3/mrt/stg/billing/db-host
  database: 
    ssm: /uc3/mrt/stg/billing/db-name
  username: 
    ssm: /uc3/mrt/stg/billing/readwrite/db-user
  password: 
    ssm: /uc3/mrt/stg/billing/readwrite/db-password
  base_url:
    env: base_url
  read_timeout:
    val: 600
  write_timeout:
    val: 600
ecs-prd:
  host: 
    ssm: /uc3/mrt/prd/billing/db-host
  database: 
    ssm: /uc3/mrt/prd/billing/db-name
  username: 
    ssm: /uc3/mrt/prd/billing/readwrite/db-user
  password: 
    ssm: /uc3/mrt/prd/billing/readwrite/db-password
  base_url:
    env: base_url
  read_timeout:
    val: 600
  write_timeout:
    val: 600
default:
  <<: *docker 