docker:
  host: 
    val: db-container
  database: 
    val: billing
  username: 
    val: user
  password: 
    val: password
  base_url:
    env: base_url
  read_timeout:
    val: 120
dockerlocal:
  host: 
    val: 127.0.0.1
  database: 
    val: billing
  username: 
    val: user
  password: 
    val: password
  base_url:
    env: base_url
  read_timeout:
    val: 120
ecs:
  host: 
    ssm: /uc3/mrt/ecs/billing/db-host
  database: 
    ssm: /uc3/mrt/ecs/billing/db-name
  username: 
    ssm: /uc3/mrt/ecs/billing/readwrite/db-user
  password: 
    ssm: /uc3/mrt/ecs/billing/readwrite/db-password
  base_url:
    env: base_url
  read_timeout:
    val: 120
default:
  host: 
    ssm: /uc3/mrt/dev/billing/db-host
  database: 
    ssm: /uc3/mrt/dev/billing/db-name
  username: 
    ssm: /uc3/mrt/dev/billing/readwrite/db-user
  password: 
    ssm: /uc3/mrt/dev/billing/readwrite/db-password
  base_url:
    env: base_url
  read_timeout:
    val: 600
  