zkconn: 
  env: ZKCONN
  default: zoo:2181
admin_host:
  env: ZK_ADMIN_HOST
  default: zoo1
admin_port:
  env: ZK_ADMIN_PORT
  default: 8080
admin_user:
  env: ZK_ADMIN_USER
  default: root
admin_pass:
  env: ZK_ADMIN_PASS
  default: root_passwd
snapshot_dir:
  env: ZK_SNAPSHOT_DIR
  default: /tdr/ingest/queue/zk-snapshots