queries:
  /init/check-nodes:
    sql: |
      select * from inv.inv_nodes
  /init/create-nodes:
    update: true
    sql: |
      insert into inv.inv_nodes(
        number,
        media_type,
        media_connectivity,
        access_mode,
        access_protocol,
        node_form,
        node_protocol,
        logical_volume,
        external_provider,
        verify_on_read,
        verify_on_write,
        base_url
      )
      select
        7777,
        'magnetic-disk',
        'cloud',
        'on-line',
        's3',
        'physical',
        'http',
        'yaml:7777',
        'nodeio',
        1,
        1,
        'http://store:8080/store'
      union
      select
        8888,
        'magnetic-disk',
        'cloud',
        'on-line',
        's3',
        'physical',
        'http',
        'yaml:8888',
        'nodeio',
        1,
        1,
        'http://store:8080/store'
      union
      select
        8889,
        'magnetic-disk',
        'cloud',
        'on-line',
        's3',
        'physical',
        'http',
        'yaml:8889',
        'nodeio',
        1,
        1,
        'http://store:8080/store'
  /init/check-node-counts:
    sql: |
      select * from billing.daily_node_counts
  /init/create-node-counts:
    update: true
    sql: |
      insert into billing.daily_node_counts(
        as_of_date,
        inv_node_id,
        number,
        object_count,
        object_count_primary,
        object_count_secondary,
        file_count,
        billable_size
      )
      select
        date(now()), id, number, 1, 0, 0, 0, 0
      from inv.inv_nodes;
  /init/create-collection-nodes:
    update: true
    sql: |
      insert into inv.inv_collections_inv_nodes(inv_collection_id, inv_node_id)
      values(
        (select id as inv_collection_id from inv.inv_collections where ark = ?),
        (select id as inv_node_id from inv.inv_nodes where number = 8888)
      )
    parameters:
    - name: ark
      type: string