queries:
  /ops/collections/storage-node-config:
    sql: |
      with node_counts as (
        select 
          inv_collection_id, 
          count(*) node_count
        from inv.inv_collections_inv_nodes
        group by inv_collection_id
      )
      select
        c.id,
        c.mnemonic,
        c.name,
        c.ark,
        '' primary_node,
        ifnull(node_count, 0) node_count,
        '' actions,
        case
          when ifnull(node_count, 0) < 2 then 'FAIL'
          else 'PASS'
        end as status
      from inv.inv_collections c
      left join node_counts nc
        on c.id = nc.inv_collection_id
      {{{COLLFILTER}}}
      order by c.mnemonic
  /ops/collections/storage-node-config/collection:
    sql: |
      with collection as (
        select ? as id
      ),
      nprimary as (
        select
          (select id from collection) as inv_collection_id,
          n.id as inv_node_id,
          'primary' as role,
          n.number as node_number,
          n.description,
          n.access_mode,
          0 as count,
          100 as pct_complete,
          '' as actions
        from inv.inv_nodes n
        where number = ?
      ),
      nsecondary as (
        select
          c.id as inv_collection_id,
          n.id as inv_node_id,
          'secondary' as role,
          n.number as node_number,
          n.description,
          n.access_mode,
          0 as count,
          100 as pct_complete,
          '' as actions
        from
          inv.inv_collections_inv_nodes cn
        join inv.inv_nodes n
          on cn.inv_node_id = n.id
        join collection c
          on cn.inv_collection_id = c.id
      ),
      actual as (
        select 
          c.id as inv_collection_id,
          n.id as inv_node_id,
          inio.role,
          n.number as node_number, 
          n.description,
          n.access_mode,
          count(*) as count,
          100 as pct_complete,
          '' as actions
        from inv.inv_collections_inv_objects icio
        inner join collection c
          on icio.inv_collection_id = c.id
        inner join inv.inv_nodes_inv_objects inio
          on icio.inv_object_id = inio.inv_object_id
        inner join inv.inv_nodes n
          on inio.inv_node_id = n.id
        group by n.id, n.number, inio.role
      ),
      pcount as (
        select ifnull(sum(count), 0) as count 
        from actual 
        where role = 'primary'
      )

      select a.*, pc.count as total from actual a, pcount pc
      where a.role = 'primary'
      union
      select a.*, pc.count as total from actual a, pcount pc
      where a.role = 'secondary'
      and exists (
          select 1 from nsecondary s 
          where a.node_number = s.node_number
        )
      union
      select 
        a.inv_collection_id,
        a.inv_node_id,
        'obsolete' as role,
        a.node_number,
        a.description,
        a.access_mode,
        a.count,
        pc.count as total,
        100 as pct_complete,
        '' as actions
      from actual a, pcount pc
      where a.role = 'secondary'
      and not exists (
          select 1 from nsecondary s
          where a.node_number = s.node_number
        )
      union
      select p.*, pc.count as total from nprimary p, pcount pc
        where not exists (
          select 1 from actual aa 
          where aa.node_number=p.node_number
        )
      union
      select s.*, pc.count as total from nsecondary s, pcount pc
        where not exists (
          select 1 from actual aa 
          where aa.node_number = s.node_number
        )
    parameters:
    - name: inv_collection_id
      type: integer
    - name: primary
      type: integer
  /ops/storage/scans:
    sql: |
      select
        n.number,
        case
          when description is null then 'No description'
          else description
        end as description,
        access_mode,
        ifnull(nc.file_count, 0) + ifnull(nc.object_count, 0) as pcount,
        iss.scan_status,
        iss.created,
        iss.updated,
        (
          select
            count(*)
          from
            inv.inv_storage_maints ism
          where
            n.id = ism.inv_node_id
          and
            maint_status = 'review'
        ) as num_review,
        (
          select
            count(*)
          from
            inv.inv_storage_maints ism
          where
            n.id = ism.inv_node_id
          and
            maint_status = 'delete'
        ) as num_deletes,
        (
          select
            count(*)
          from
            inv.inv_storage_maints ism
          where
            n.id = ism.inv_node_id
          and
            maint_status = 'hold'
        ) as num_holds,
        (
          select
            count(*)
          from
            inv.inv_storage_maints ism
          where
            n.id = ism.inv_node_id
        ) as num_maints,
        ifnull(iss.keys_processed, 0) as keys_processed,
        case
          when ifnull(nc.file_count, 0) + ifnull(nc.object_count, 0) = 0 then 100
          else round((ifnull(iss.keys_processed, 0) / (ifnull(nc.file_count, 0) + ifnull(nc.object_count, 0))) * 100, 2)
        end as percent_complete,
        iss.id as inv_scan_id,
        '' actions
      from
        inv.inv_nodes n
      left join billing.node_counts nc
        on n.id = nc.inv_node_id
      left join (
        select
          inv_node_id,
          max(id) as inv_storage_scan_id
        from
          inv.inv_storage_scans
        group by
          inv_node_id
      ) ls
        on n.id = ls.inv_node_id
      left join inv.inv_storage_scans iss
        on ls.inv_storage_scan_id = iss.id
      order by
        pcount desc
  /ops/log-consistency:
    update: true
    sql: |
      insert into daily_consistency_checks(check_name, status)
      values(?, ?)
    parameters:
      - name: check_name
        type: string
      - name: status
        type: string