queries:
  /ops/collections/storage-node-config:
    sql: |
      with node_counts as (
        select 
          inv_collection_id, 
          count(*) node_count
        from inv.inv_collections_inv_nodes
        group by inv_collection_id
      )
      select
        c.id,
        c.mnemonic,
        c.name,
        c.ark,
        '' primary_node,
        ifnull(node_count, 0) node_count,
        '' actions,
        case
          when ifnull(node_count, 0) < 2 then 'FAIL'
          else 'PASS'
        end as status
      from inv.inv_collections c
      left join node_counts nc
        on c.id = nc.inv_collection_id
      {{{COLLFILTER}}}
      order by c.mnemonic
  /ops/collections/storage-node-config/collection:
    sql: |
      with collection as (
        select ? as id
      ),
      nprimary as (
        select
          ? as num,
          'primary' as role
      ),
      nsecondary as (
        select
          n.number as num,
          'secondary' as role
        from
          inv.inv_collections_inv_nodes cn
        join inv.inv_nodes n
          on cn.inv_node_id = n.id
        join collection c
          on cn.inv_collection_id = c.id
      )

      select 0 as id, num as node_number, role, 0 as count from nprimary
      union
      select 0 as id,num as node_number, role, 0 as count from nsecondary
      union
      select 
        n.id,
        n.number as node_number, 
        inio.role,
        count(*) as count
      from inv.inv_collections_inv_objects icio
      inner join collection c
        on icio.inv_collection_id = c.id
      inner join inv.inv_nodes_inv_objects inio
        on icio.inv_object_id = inio.inv_object_id
      inner join inv.inv_nodes n
        on inio.inv_node_id = n.id
      group by n.id, n.number, inio.role
    parameters:
    - name: inv_collection_id
      type: integer
    - name: primary
      type: integer
  /ops/storage/scans:
    sql: |
      select
        n.number,
        case
          when description is null then 'No description'
          else description
        end as description,
        access_mode,
        ifnull(nc.file_count, 0) + ifnull(nc.object_count, 0) as pcount,
        iss.scan_status,
        iss.created,
        iss.updated,
        (
          select
            count(*)
          from
            inv.inv_storage_maints ism
          where
            n.id = ism.inv_node_id
          and
            maint_status = 'review'
        ) as num_review,
        (
          select
            count(*)
          from
            inv.inv_storage_maints ism
          where
            n.id = ism.inv_node_id
          and
            maint_status = 'delete'
        ) as num_deletes,
        (
          select
            count(*)
          from
            inv.inv_storage_maints ism
          where
            n.id = ism.inv_node_id
          and
            maint_status = 'hold'
        ) as num_holds,
        (
          select
            count(*)
          from
            inv.inv_storage_maints ism
          where
            n.id = ism.inv_node_id
        ) as num_maints,
        ifnull(iss.keys_processed, 0) as keys_processed,
        case
          when ifnull(nc.file_count, 0) + ifnull(nc.object_count, 0) = 0 then 100
          else round((ifnull(iss.keys_processed, 0) / (ifnull(nc.file_count, 0) + ifnull(nc.object_count, 0))) * 100, 2)
        end as percent_complete,
        iss.id as inv_scan_id,
        '' actions
      from
        inv.inv_nodes n
      left join billing.node_counts nc
        on n.id = nc.inv_node_id
      left join (
        select
          inv_node_id,
          max(id) as inv_storage_scan_id
        from
          inv.inv_storage_scans
        group by
          inv_node_id
      ) ls
        on n.id = ls.inv_node_id
      left join inv.inv_storage_scans iss
        on ls.inv_storage_scan_id = iss.id
      order by
        pcount desc
  /ops/log-consistency:
    update: true
    sql: |
      insert into daily_consistency_checks(check_name, status)
      values(?, ?)
    parameters:
      - name: check_name
        type: string
      - name: status
        type: string